INFO 2025-09-08 00:06:44,425 [main.py (startup)] BOT STARTED
INFO 2025-09-08 00:06:44,631 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
ERROR 2025-09-08 00:06:45,545 [user.py (__call__)] Middleware get user error 500 Произошла ошибка. Повторите попытку позже.
INFO 2025-09-08 00:06:49,743 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
ERROR 2025-09-08 00:06:50,513 [user.py (__call__)] Middleware get user error 500 Произошла ошибка. Повторите попытку позже.
INFO 2025-09-08 00:08:33,470 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
ERROR 2025-09-08 00:08:34,285 [user.py (__call__)] Middleware get user error 500 Произошла ошибка. Повторите попытку позже.
INFO 2025-09-08 00:08:49,798 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-08 00:08:55,177 [main.py (startup)] BOT STARTED
INFO 2025-09-08 00:08:58,984 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-08 00:09:04,173 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-08 00:09:13,517 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-08 00:09:19,380 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-08 09:01:57,452 [main.py (startup)] BOT STARTED
INFO 2025-09-08 09:02:48,445 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK search
INFO 2025-09-08 09:02:58,459 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER state_user_router CALLBACK skins_search
INFO 2025-09-08 09:03:01,993 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-08 09:03:04,268 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-08 09:03:06,896 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK empty_button
INFO 2025-09-08 09:03:12,129 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_skin_search
INFO 2025-09-08 09:03:14,740 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_skin_search
INFO 2025-09-08 09:03:20,278 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-08 09:03:23,064 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-08 09:03:42,692 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-08 09:03:47,067 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_portfolio_skin
INFO 2025-09-08 09:03:52,758 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_portfolio_skin
INFO 2025-09-08 09:03:59,742 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_portfolio_skin
INFO 2025-09-08 09:04:01,583 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-08 09:04:33,834 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK start
INFO 2025-09-08 09:04:36,452 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK account
INFO 2025-09-08 09:04:53,866 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-08 10:34:11,833 [main.py (startup)] BOT STARTED
INFO 2025-09-08 10:34:27,584 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK steam_inventory
ERROR 2025-09-08 10:34:28,809 [user.py (__call__)] Middleware get user error 500 Произошла ошибка. Повторите попытку позже.
INFO 2025-09-08 10:34:45,562 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-08 10:35:42,202 [main.py (startup)] BOT STARTED
INFO 2025-09-08 10:35:50,814 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK steam_inventory
INFO 2025-09-08 10:35:56,385 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 10:36:20,587 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-08 10:36:56,776 [main.py (startup)] BOT STARTED
INFO 2025-09-08 10:37:06,476 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK steam_inventory
INFO 2025-09-08 10:37:10,200 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 10:37:12,198 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 10:37:14,397 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 10:37:16,134 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 10:37:18,245 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 10:37:20,380 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
ERROR 2025-09-08 10:37:20,705 [log.py (__call__)] 'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\log.py", line 29, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\user.py", line 73, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram_tool\depend\components\inner_middleware.py", line 42, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\handlers\callbacks\user\router.py", line 132, in paginate_steam_inventory_skin
    response = await client.user.get_steam_inventory_user(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\infrastracture\http\fastfy\clients\user.py", line 82, in get_steam_inventory_user
    return SkinsOnPageSchema(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\pydantic\main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\schemas\fastfy\schema.py", line 50, in validator
    data["skins"] = [
TypeError: 'NoneType' object is not iterable
INFO 2025-09-08 10:38:16,309 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-08 10:41:52,999 [main.py (startup)] BOT STARTED
INFO 2025-09-08 10:42:02,997 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK steam_inventory
INFO 2025-09-08 10:42:06,523 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 10:42:08,156 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 10:42:12,329 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 10:42:14,432 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 10:42:16,569 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 10:42:18,570 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 10:42:20,604 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
ERROR 2025-09-08 10:42:20,900 [log.py (__call__)] 'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\log.py", line 29, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\user.py", line 73, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram_tool\depend\components\inner_middleware.py", line 42, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\handlers\callbacks\user\router.py", line 132, in paginate_steam_inventory_skin
    response = await client.user.get_steam_inventory_user(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\infrastracture\http\fastfy\clients\user.py", line 82, in get_steam_inventory_user
    return SkinsOnPageSchema(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\pydantic\main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\schemas\fastfy\schema.py", line 50, in validator
    data["skins"] = [
TypeError: 'NoneType' object is not iterable
INFO 2025-09-08 10:42:26,263 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-08 11:28:34,609 [main.py (startup)] BOT STARTED
INFO 2025-09-08 11:28:39,136 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK steam_inventory
INFO 2025-09-08 11:28:47,569 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK steam_inventory
INFO 2025-09-08 11:28:52,002 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 11:28:53,480 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 11:28:55,219 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 11:28:56,851 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 11:28:58,493 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 11:29:01,616 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
ERROR 2025-09-08 11:29:02,005 [log.py (__call__)] 'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\log.py", line 29, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\user.py", line 73, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram_tool\depend\components\inner_middleware.py", line 42, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\handlers\callbacks\user\router.py", line 132, in paginate_steam_inventory_skin
    response = await client.user.get_steam_inventory_user(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\infrastracture\http\fastfy\clients\user.py", line 82, in get_steam_inventory_user
    return SkinsOnPageSchema(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\pydantic\main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\schemas\fastfy\schema.py", line 50, in validator
    data["skins"] = [
TypeError: 'NoneType' object is not iterable
INFO 2025-09-08 11:30:44,102 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK steam_inventory
INFO 2025-09-08 11:30:47,095 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 11:30:48,573 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 11:30:50,474 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 11:30:52,237 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 11:30:54,164 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 11:30:55,987 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
ERROR 2025-09-08 11:30:56,353 [log.py (__call__)] 'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\log.py", line 29, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\user.py", line 73, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram_tool\depend\components\inner_middleware.py", line 42, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\handlers\callbacks\user\router.py", line 132, in paginate_steam_inventory_skin
    response = await client.user.get_steam_inventory_user(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\infrastracture\http\fastfy\clients\user.py", line 82, in get_steam_inventory_user
    return SkinsOnPageSchema(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\pydantic\main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\schemas\fastfy\schema.py", line 50, in validator
    data["skins"] = [
TypeError: 'NoneType' object is not iterable
INFO 2025-09-08 11:37:06,803 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
ERROR 2025-09-08 11:37:07,787 [log.py (__call__)] 'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\log.py", line 29, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\user.py", line 73, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram_tool\depend\components\inner_middleware.py", line 42, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\handlers\callbacks\user\router.py", line 132, in paginate_steam_inventory_skin
    response = await client.user.get_steam_inventory_user(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\infrastracture\http\fastfy\clients\user.py", line 82, in get_steam_inventory_user
    return SkinsOnPageSchema(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\pydantic\main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\schemas\fastfy\schema.py", line 50, in validator
    data["skins"] = [
TypeError: 'NoneType' object is not iterable
INFO 2025-09-08 11:37:24,849 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
ERROR 2025-09-08 11:37:25,221 [log.py (__call__)] 'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\log.py", line 29, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\user.py", line 73, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram_tool\depend\components\inner_middleware.py", line 42, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\handlers\callbacks\user\router.py", line 132, in paginate_steam_inventory_skin
    response = await client.user.get_steam_inventory_user(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\infrastracture\http\fastfy\clients\user.py", line 82, in get_steam_inventory_user
    return SkinsOnPageSchema(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\pydantic\main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\schemas\fastfy\schema.py", line 50, in validator
    data["skins"] = [
TypeError: 'NoneType' object is not iterable
INFO 2025-09-08 11:40:30,524 [main.py (startup)] BOT STARTED
INFO 2025-09-08 11:40:51,493 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 11:41:11,330 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 11:41:15,039 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 11:41:17,516 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 11:41:19,658 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 11:49:14,735 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK search
INFO 2025-09-08 11:49:23,792 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER state_user_router CALLBACK skins_search
INFO 2025-09-08 11:49:29,668 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-08 11:49:35,410 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-08 11:49:43,930 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-08 11:49:45,535 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-08 11:49:47,080 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-08 11:49:50,995 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-08 11:49:54,691 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_skin_search
INFO 2025-09-08 11:49:57,014 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_skin_search
INFO 2025-09-08 11:50:00,909 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-08 11:50:25,011 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-08 11:58:19,547 [main.py (startup)] BOT STARTED
INFO 2025-09-08 11:58:33,950 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK steam_inventory
ERROR 2025-09-08 11:58:35,242 [user.py (__call__)] Middleware get user error 500 Произошла ошибка. Повторите попытку позже.
INFO 2025-09-08 11:59:36,023 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-08 11:59:42,652 [main.py (startup)] BOT STARTED
INFO 2025-09-08 11:59:51,511 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK steam_inventory
INFO 2025-09-08 11:59:58,876 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_steam_inventory_skin
INFO 2025-09-08 12:00:01,035 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_steam_inventory_skin
INFO 2025-09-08 12:00:06,100 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-08 12:00:09,278 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_steam_inventory_skin
INFO 2025-09-08 12:00:12,909 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_portfolio_skin
INFO 2025-09-08 12:00:15,227 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_portfolio_skin
INFO 2025-09-08 12:00:23,228 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_portfolio_skin
INFO 2025-09-08 12:00:25,665 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_portfolio_skin
INFO 2025-09-08 12:00:27,839 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-08 12:00:32,189 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_portfolio_skin
INFO 2025-09-08 12:00:34,713 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_portfolio_skin
INFO 2025-09-08 12:00:46,673 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK steam_inventory
INFO 2025-09-08 12:00:48,791 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 12:00:50,730 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 12:00:52,477 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 12:00:54,124 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 12:01:00,528 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 12:01:02,540 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 12:01:07,099 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 12:01:08,719 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 12:01:17,227 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-08 12:49:41,215 [main.py (startup)] BOT STARTED
INFO 2025-09-08 12:49:46,014 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
ERROR 2025-09-08 12:49:46,722 [user.py (__call__)] Middleware get user error 500 Произошла ошибка. Повторите попытку позже.
INFO 2025-09-08 12:49:58,266 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-08 12:50:45,147 [main.py (startup)] BOT STARTED
INFO 2025-09-08 12:50:54,692 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-08 12:50:58,887 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_portfolio_skin
INFO 2025-09-08 12:51:00,575 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_portfolio_skin
INFO 2025-09-08 12:51:11,500 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_portfolio_skin
INFO 2025-09-08 12:51:13,714 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_portfolio_skin
INFO 2025-09-08 12:51:19,090 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_portfolio_skin
INFO 2025-09-08 12:51:34,360 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-08 16:52:40,675 [main.py (startup)] BOT STARTED
INFO 2025-09-08 16:52:49,036 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
ERROR 2025-09-08 16:52:50,128 [user.py (__call__)] Middleware get user error 500 Произошла ошибка. Повторите попытку позже.
INFO 2025-09-08 16:53:02,087 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-08 16:53:38,586 [main.py (startup)] BOT STARTED
INFO 2025-09-08 16:53:42,122 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-08 16:53:48,274 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_portfolio_skin
INFO 2025-09-08 16:54:29,546 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_portfolio_skin
INFO 2025-09-08 16:56:55,172 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_portfolio_skin
ERROR 2025-09-08 16:56:55,669 [log.py (__call__)] 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
Traceback (most recent call last):
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\log.py", line 29, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\user.py", line 73, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram_tool\depend\components\inner_middleware.py", line 42, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\handlers\callbacks\user\router.py", line 128, in click_portfolio_skin
    await query.message.answer(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\types\message.py", line 2244, in answer
    return SendMessage(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\pydantic\main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for SendMessage
text
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.11/v/string_type
INFO 2025-09-08 16:57:12,836 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-08 17:08:58,671 [main.py (startup)] BOT STARTED
INFO 2025-09-08 17:09:06,386 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_portfolio_skin
ERROR 2025-09-08 17:09:08,240 [log.py (__call__)] Telegram server says - Bad Request: can't parse entities: Character '-' is reserved and must be escaped with the preceding '\'
Traceback (most recent call last):
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\log.py", line 29, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\user.py", line 73, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram_tool\depend\components\inner_middleware.py", line 42, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\handlers\callbacks\user\router.py", line 134, in click_portfolio_skin
    await query.message.answer_photo(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\client\bot.py", line 485, in __call__
    return await self.session(self, method, timeout=request_timeout)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\client\session\aiohttp.py", line 185, in make_request
    response = self.check_response(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '-' is reserved and must be escaped with the preceding '\'
INFO 2025-09-08 17:09:18,313 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-08 17:09:40,181 [main.py (startup)] BOT STARTED
INFO 2025-09-08 17:09:52,489 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-08 17:09:57,977 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_portfolio_skin
ERROR 2025-09-08 17:09:58,956 [log.py (__call__)] Telegram server says - Bad Request: can't parse entities: Character '.' is reserved and must be escaped with the preceding '\'
Traceback (most recent call last):
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\log.py", line 29, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\user.py", line 73, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram_tool\depend\components\inner_middleware.py", line 42, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\handlers\callbacks\user\router.py", line 134, in click_portfolio_skin
    await query.message.answer_photo(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\client\bot.py", line 485, in __call__
    return await self.session(self, method, timeout=request_timeout)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\client\session\aiohttp.py", line 185, in make_request
    response = self.check_response(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '.' is reserved and must be escaped with the preceding '\'
INFO 2025-09-08 17:10:10,914 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-08 17:10:22,728 [main.py (startup)] BOT STARTED
INFO 2025-09-08 17:10:47,864 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_portfolio_skin
INFO 2025-09-08 17:11:07,883 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-08 17:20:11,599 [main.py (startup)] BOT STARTED
INFO 2025-09-08 17:20:20,434 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_portfolio_skin
INFO 2025-09-08 17:20:30,051 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK delete_messagen
INFO 2025-09-08 17:20:33,481 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK profile
ERROR 2025-09-08 17:20:33,482 [log.py (__call__)] profile() missing 1 required positional argument: 'user'
Traceback (most recent call last):
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\log.py", line 29, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\user.py", line 73, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram_tool\depend\components\inner_middleware.py", line 42, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
TypeError: profile() missing 1 required positional argument: 'user'
INFO 2025-09-08 17:20:44,983 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-08 17:20:48,123 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_portfolio_skin
INFO 2025-09-08 17:20:50,132 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_portfolio_skin
INFO 2025-09-08 17:21:04,450 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK delete_portfolio_skin
INFO 2025-09-08 17:21:07,540 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_portfolio_skin
INFO 2025-09-08 17:21:09,469 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_portfolio_skin
INFO 2025-09-08 17:21:13,722 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_portfolio_skin
INFO 2025-09-08 17:21:15,134 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_portfolio_skin
INFO 2025-09-08 17:21:16,973 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_portfolio_skin
INFO 2025-09-08 17:21:21,163 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK delete_portfolio_skin
INFO 2025-09-08 17:22:36,671 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-08 17:22:51,221 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK search
INFO 2025-09-08 17:22:55,253 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER state_user_router CALLBACK skins_search
ERROR 2025-09-08 17:22:55,679 [log.py (__call__)] Separator symbol ':' can not be used in value skin_name='CS:GO Weapon Case 3'
Traceback (most recent call last):
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\log.py", line 29, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\user.py", line 73, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram_tool\depend\components\inner_middleware.py", line 42, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\handlers\states\user\router.py", line 76, in skins_search
    reply_markup=paginate_buttons(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\utils\buttons\inline\user\buttons.py", line 49, in paginate_buttons
    ).pack()
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\filters\callback_data.py", line 101, in pack
    raise ValueError(
ValueError: Separator symbol ':' can not be used in value skin_name='CS:GO Weapon Case 3'
INFO 2025-09-08 17:24:08,886 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-08 17:25:30,495 [main.py (startup)] BOT STARTED
INFO 2025-09-08 17:25:44,073 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK search
ERROR 2025-09-08 17:25:45,197 [user.py (__call__)] Middleware get user error 500 Произошла ошибка. Повторите попытку позже.
INFO 2025-09-08 17:26:00,762 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-08 17:27:12,619 [main.py (startup)] BOT STARTED
INFO 2025-09-08 17:27:12,821 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK search
INFO 2025-09-08 17:27:18,825 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER state_user_router CALLBACK skins_search
INFO 2025-09-08 17:27:25,378 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_skin_search
INFO 2025-09-08 17:27:57,488 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-08 17:27:59,513 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_portfolio_skin
INFO 2025-09-08 17:28:09,907 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK delete_messagen
INFO 2025-09-08 17:28:11,636 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_portfolio_skin
INFO 2025-09-08 17:28:15,045 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK delete_portfolio_skin
INFO 2025-09-08 17:28:33,377 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_portfolio_skin
INFO 2025-09-08 17:28:36,944 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK delete_portfolio_skin
INFO 2025-09-08 17:28:44,930 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_portfolio_skin
INFO 2025-09-08 17:30:24,915 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK delete_portfolio_skin
INFO 2025-09-08 17:30:45,107 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_portfolio_skin
INFO 2025-09-08 17:30:49,263 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK delete_portfolio_skin
INFO 2025-09-08 17:30:56,947 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_portfolio_skin
INFO 2025-09-08 17:31:01,031 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-08 17:31:11,380 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-08 17:31:13,541 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-08 17:31:16,135 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-08 17:31:18,860 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-08 17:31:20,754 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-08 17:31:22,289 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-08 17:31:23,548 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-08 17:31:25,731 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK empty_button
INFO 2025-09-08 17:31:30,959 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-08 17:31:34,593 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-08 17:31:38,121 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-08 17:31:42,345 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_skin_search
INFO 2025-09-08 17:31:46,282 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_skin_search
INFO 2025-09-08 17:31:49,898 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-08 17:31:55,310 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-08 17:31:58,470 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_portfolio_skin
INFO 2025-09-08 17:32:07,295 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK account
INFO 2025-09-08 17:32:10,338 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK start
INFO 2025-09-08 17:32:17,119 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK steam_inventory
INFO 2025-09-08 17:32:25,129 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 17:32:26,968 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 17:32:31,794 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 17:32:32,959 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 17:32:34,906 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_steam_inventory_skin
INFO 2025-09-08 17:32:36,564 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_steam_inventory_skin
INFO 2025-09-08 17:32:40,799 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_steam_inventory_skin
INFO 2025-09-08 17:32:42,276 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_steam_inventory_skin
INFO 2025-09-08 17:32:43,747 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 17:32:45,931 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_steam_inventory_skin
INFO 2025-09-08 17:32:48,702 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_steam_inventory_skin
INFO 2025-09-08 17:32:50,009 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_steam_inventory_skin
INFO 2025-09-08 17:32:51,628 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_steam_inventory_skin
INFO 2025-09-08 17:32:56,336 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_steam_inventory_skin
INFO 2025-09-08 17:33:49,015 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-08 17:35:02,833 [main.py (startup)] BOT STARTED
INFO 2025-09-08 17:35:07,539 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_steam_inventory_skin
INFO 2025-09-08 17:35:17,862 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_steam_inventory_skin
INFO 2025-09-08 17:35:19,997 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 17:35:30,642 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_steam_inventory_skin
INFO 2025-09-08 17:35:48,213 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_steam_inventory_skin
INFO 2025-09-08 17:35:51,126 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 17:35:55,884 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 17:36:00,053 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_steam_inventory_skin
INFO 2025-09-08 17:36:01,871 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_steam_inventory_skin
INFO 2025-09-08 17:36:04,978 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_steam_inventory_skin
INFO 2025-09-08 17:36:07,493 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_steam_inventory_skin
INFO 2025-09-08 17:36:10,692 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-08 17:36:14,906 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_portfolio_skin
INFO 2025-09-08 17:36:18,484 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_portfolio_skin
INFO 2025-09-08 17:36:25,840 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK empty_button
INFO 2025-09-08 17:36:27,638 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_portfolio_skin
ERROR 2025-09-08 17:36:28,654 [log.py (__call__)] Telegram server says - Bad Request: can't parse entities: Character '-' is reserved and must be escaped with the preceding '\'
Traceback (most recent call last):
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\log.py", line 29, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\user.py", line 73, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram_tool\depend\components\inner_middleware.py", line 42, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\handlers\callbacks\user\router.py", line 134, in click_portfolio_skin
    await query.message.answer_photo(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\client\bot.py", line 485, in __call__
    return await self.session(self, method, timeout=request_timeout)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\client\session\aiohttp.py", line 185, in make_request
    response = self.check_response(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '-' is reserved and must be escaped with the preceding '\'
INFO 2025-09-08 17:37:32,672 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-08 17:39:41,375 [main.py (startup)] BOT STARTED
INFO 2025-09-08 17:39:51,202 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_portfolio_skin
ERROR 2025-09-08 17:39:52,884 [log.py (__call__)] Telegram server says - Bad Request: can't parse entities: Character '|' is reserved and must be escaped with the preceding '\'
Traceback (most recent call last):
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\log.py", line 29, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\user.py", line 73, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram_tool\depend\components\inner_middleware.py", line 42, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\handlers\callbacks\user\router.py", line 134, in click_portfolio_skin
    await query.message.answer_photo(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\client\bot.py", line 485, in __call__
    return await self.session(self, method, timeout=request_timeout)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\client\session\aiohttp.py", line 185, in make_request
    response = self.check_response(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse entities: Character '|' is reserved and must be escaped with the preceding '\'
INFO 2025-09-08 17:40:03,880 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-08 17:51:26,122 [main.py (startup)] BOT STARTED
INFO 2025-09-08 17:51:41,032 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_portfolio_skin
