INFO 2025-09-06 18:52:45,336 [main.py (startup)] BOT STARTED
INFO 2025-09-06 18:53:02,360 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK search
INFO 2025-09-06 18:53:08,769 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER state_user_router CALLBACK skins_search
ERROR 2025-09-06 18:53:09,515 [log.py (__call__)] 1 validation error for SkinsOnPageSchema
skin_model
  Input should be a valid dictionary or instance of BaseModel [type=model_type, input_value=<class 'bot.schemas.fastfy.schema.SkinSchema'>, input_type=ModelMetaclass]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
Traceback (most recent call last):
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\log.py", line 29, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\user.py", line 64, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram_tool\depend\components\inner_middleware.py", line 42, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\handlers\states\user\router.py", line 61, in skins_search
    response = await client.skin.search_skins(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\infrastracture\http\fastfy\clients\skin.py", line 56, in search_skins
    return SkinsOnPageSchema(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\pydantic\main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for SkinsOnPageSchema
skin_model
  Input should be a valid dictionary or instance of BaseModel [type=model_type, input_value=<class 'bot.schemas.fastfy.schema.SkinSchema'>, input_type=ModelMetaclass]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
INFO 2025-09-06 18:53:53,637 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-06 18:53:59,242 [main.py (startup)] BOT STARTED
INFO 2025-09-06 18:54:10,914 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK search
INFO 2025-09-06 18:54:19,769 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER state_user_router CALLBACK skins_search
ERROR 2025-09-06 18:54:20,438 [log.py (__call__)] 1 validation error for SkinsOnPageSchema
  Input should be a valid dictionary or instance of SkinSchema [type=model_type, input_value=<unprintable BaseModel object>, input_type=BaseModel]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
Traceback (most recent call last):
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\log.py", line 29, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\user.py", line 64, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram_tool\depend\components\inner_middleware.py", line 42, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\handlers\states\user\router.py", line 61, in skins_search
    response = await client.skin.search_skins(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\infrastracture\http\fastfy\clients\skin.py", line 56, in search_skins
    return SkinsOnPageSchema(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\pydantic\main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for SkinsOnPageSchema
  Input should be a valid dictionary or instance of SkinSchema [type=model_type, input_value=<unprintable BaseModel object>, input_type=BaseModel]
    For further information visit https://errors.pydantic.dev/2.11/v/model_type
INFO 2025-09-06 18:59:54,791 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-06 19:00:01,042 [main.py (startup)] BOT STARTED
INFO 2025-09-06 19:00:07,596 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK search
ERROR 2025-09-06 19:00:08,938 [user.py (__call__)] Middleware get user error 500 Произошла ошибка. Повторите попытку позже.
INFO 2025-09-06 19:00:28,605 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK search
INFO 2025-09-06 19:00:33,224 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER state_user_router CALLBACK skins_search
ERROR 2025-09-06 19:00:34,034 [log.py (__call__)] 'SkinsOnPageSchema' object has no attribute 'status'
Traceback (most recent call last):
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\log.py", line 29, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\user.py", line 64, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram_tool\depend\components\inner_middleware.py", line 42, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\handlers\states\user\router.py", line 66, in skins_search
    if response.status in [DetailStatus.DONE, DetailStatus.ERROR]:
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\pydantic\main.py", line 991, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'SkinsOnPageSchema' object has no attribute 'status'
INFO 2025-09-06 19:02:43,324 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-06 19:02:48,768 [main.py (startup)] BOT STARTED
INFO 2025-09-06 19:02:55,491 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK search
INFO 2025-09-06 19:03:00,235 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER state_user_router CALLBACK skins_search
ERROR 2025-09-06 19:03:00,982 [log.py (__call__)] 'SkinSchema' object has no attribute 'skins'
Traceback (most recent call last):
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\log.py", line 29, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\user.py", line 64, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram_tool\depend\components\inner_middleware.py", line 42, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\handlers\states\user\router.py", line 73, in skins_search
    reply_markup=search_buttons(skins=response)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\utils\buttons\inline\user\buttons.py", line 69, in search_buttons
    builder.adjust(*[1 for _ in skin.skins], 3)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\pydantic\main.py", line 991, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'SkinSchema' object has no attribute 'skins'
INFO 2025-09-06 19:03:26,757 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-06 19:04:24,466 [main.py (startup)] BOT STARTED
INFO 2025-09-06 19:04:30,127 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK search
INFO 2025-09-06 19:04:34,280 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER state_user_router CALLBACK skins_search
ERROR 2025-09-06 19:04:35,094 [log.py (__call__)] Telegram server says - Bad Request: can't parse inline keyboard button: Text buttons are unallowed in the inline keyboard
Traceback (most recent call last):
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\log.py", line 29, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\user.py", line 64, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram_tool\depend\components\inner_middleware.py", line 42, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\handlers\states\user\router.py", line 71, in skins_search
    await message.answer(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\client\bot.py", line 485, in __call__
    return await self.session(self, method, timeout=request_timeout)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\client\session\aiohttp.py", line 185, in make_request
    response = self.check_response(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: can't parse inline keyboard button: Text buttons are unallowed in the inline keyboard
INFO 2025-09-06 19:04:47,497 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-06 19:06:59,431 [main.py (startup)] BOT STARTED
INFO 2025-09-06 19:07:07,447 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK search
INFO 2025-09-06 19:07:12,085 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER state_user_router CALLBACK skins_search
INFO 2025-09-06 19:07:21,067 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-06 19:07:34,689 [main.py (startup)] BOT STARTED
INFO 2025-09-06 19:07:40,627 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK search
INFO 2025-09-06 19:07:45,440 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER state_user_router CALLBACK skins_search
INFO 2025-09-06 19:08:28,561 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-06 19:08:32,657 [main.py (startup)] BOT STARTED
INFO 2025-09-06 19:08:35,032 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK search
INFO 2025-09-06 19:08:39,522 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER state_user_router CALLBACK skins_search
INFO 2025-09-06 19:08:57,293 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-06 22:15:12,461 [main.py (startup)] BOT STARTED
INFO 2025-09-06 22:15:25,202 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK search
INFO 2025-09-06 22:15:34,209 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER state_user_router CALLBACK skins_search
ERROR 2025-09-06 22:15:35,270 [log.py (__call__)] search_buttons() missing 1 required positional argument: 'query'
Traceback (most recent call last):
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\log.py", line 29, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\user.py", line 64, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram_tool\depend\components\inner_middleware.py", line 42, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\handlers\states\user\router.py", line 72, in skins_search
    reply_markup=search_buttons(skins=response)
TypeError: search_buttons() missing 1 required positional argument: 'query'
INFO 2025-09-06 22:15:51,089 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-06 22:15:57,098 [main.py (startup)] BOT STARTED
INFO 2025-09-06 22:16:08,156 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK search
INFO 2025-09-06 22:16:12,790 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER state_user_router CALLBACK skins_search
INFO 2025-09-06 22:16:16,868 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-06 22:16:22,516 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-06 22:16:34,924 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
ERROR 2025-09-06 22:16:37,306 [log.py (__call__)] Telegram server says - Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
Traceback (most recent call last):
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\log.py", line 29, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\user.py", line 64, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram_tool\depend\components\inner_middleware.py", line 42, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\handlers\callbacks\user\router.py", line 55, in paginate_skin_search
    await query.message.edit_reply_markup(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\methods\base.py", line 84, in emit
    return await bot(self)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\client\bot.py", line 485, in __call__
    return await self.session(self, method, timeout=request_timeout)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\client\session\base.py", line 254, in __call__
    return cast(TelegramType, await middleware(bot, method))
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\client\session\aiohttp.py", line 185, in make_request
    response = self.check_response(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
INFO 2025-09-06 22:17:45,901 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-06 22:18:06,357 [main.py (startup)] BOT STARTED
INFO 2025-09-06 22:18:09,393 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK search
INFO 2025-09-06 22:18:13,604 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER state_user_router CALLBACK skins_search
INFO 2025-09-06 22:18:19,033 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-06 22:18:25,584 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-06 22:18:35,232 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-06 22:19:32,708 [main.py (startup)] BOT STARTED
INFO 2025-09-06 22:19:37,970 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK search
INFO 2025-09-06 22:19:42,379 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER state_user_router CALLBACK skins_search
INFO 2025-09-06 22:19:46,787 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-06 22:19:49,155 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-06 22:19:53,976 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-06 22:20:00,010 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-06 22:20:03,571 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-06 22:20:07,367 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK empty_button
INFO 2025-09-06 22:20:09,508 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-06 22:20:11,869 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-06 22:20:14,137 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-06 22:20:36,339 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-06 22:20:38,645 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-06 22:21:10,151 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-06 22:21:43,722 [main.py (startup)] BOT STARTED
INFO 2025-09-06 22:21:49,451 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK search
INFO 2025-09-06 22:21:57,256 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER state_user_router CALLBACK skins_search
INFO 2025-09-06 22:22:00,257 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_skin_search
INFO 2025-09-06 22:23:28,972 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_skin_search
INFO 2025-09-06 22:27:55,803 [main.py (startup)] BOT STARTED
INFO 2025-09-06 22:28:15,973 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_skin_search
INFO 2025-09-06 22:28:23,474 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_skin_search
INFO 2025-09-06 22:28:29,107 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_skin_search
INFO 2025-09-06 22:32:40,273 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-06 22:35:37,756 [main.py (startup)] BOT STARTED
INFO 2025-09-06 22:35:52,099 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_skin_search
INFO 2025-09-06 22:37:43,892 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_skin_search
INFO 2025-09-06 22:38:50,959 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-06 22:39:33,839 [main.py (startup)] BOT STARTED
INFO 2025-09-06 22:39:44,790 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_skin_search
INFO 2025-09-06 22:39:55,093 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK search
INFO 2025-09-06 22:39:59,055 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER state_user_router CALLBACK skins_search
INFO 2025-09-06 22:40:01,802 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_skin_search
INFO 2025-09-06 22:40:36,291 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-06 22:41:23,054 [main.py (startup)] BOT STARTED
INFO 2025-09-06 22:41:28,826 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK search
INFO 2025-09-06 22:41:33,990 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER state_user_router CALLBACK skins_search
INFO 2025-09-06 22:41:37,018 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_skin_search
INFO 2025-09-06 22:41:53,663 [main.py (shutdown)] BOT SHUTDOWN
