INFO 2025-09-07 12:03:58,014 [main.py (startup)] BOT STARTED
INFO 2025-09-07 12:04:02,108 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK search
INFO 2025-09-07 12:04:30,169 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER state_user_router CALLBACK skins_search
INFO 2025-09-07 12:04:34,627 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-07 12:04:37,795 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-07 12:04:41,148 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK empty_button
INFO 2025-09-07 12:04:43,675 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-07 12:04:47,287 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_skin_search
INFO 2025-09-07 12:04:59,949 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_skin_search
INFO 2025-09-07 12:05:07,655 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-07 12:05:12,487 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-07 12:07:34,322 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK search
INFO 2025-09-07 12:07:38,155 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER state_user_router CALLBACK skins_search
ERROR 2025-09-07 12:07:39,168 [log.py (__call__)] 5 validation errors for SkinsOnPageSchema
skin_price_info.update_mode
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='HIGH', input_type=str]
    For further information visit https://errors.pydantic.dev/2.11/v/int_parsing
skin_price_info.price
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.11/v/float_type
skin_price_info.price_at_1_day
  Field required [type=missing, input_value={'skin_name': 'AK-47 | Le...ice_last_365_day': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
skin_price_info.price_at_30_day
  Field required [type=missing, input_value={'skin_name': 'AK-47 | Le...ice_last_365_day': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
skin_price_info.price_at_365_day
  Field required [type=missing, input_value={'skin_name': 'AK-47 | Le...ice_last_365_day': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
Traceback (most recent call last):
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\log.py", line 29, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\user.py", line 64, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram_tool\depend\components\inner_middleware.py", line 42, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\handlers\states\user\router.py", line 62, in skins_search
    response = await client.skin.search_skins(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\infrastracture\http\fastfy\clients\skin.py", line 56, in search_skins
    return SkinsOnPageSchema(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\pydantic\main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 5 validation errors for SkinsOnPageSchema
skin_price_info.update_mode
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='HIGH', input_type=str]
    For further information visit https://errors.pydantic.dev/2.11/v/int_parsing
skin_price_info.price
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.11/v/float_type
skin_price_info.price_at_1_day
  Field required [type=missing, input_value={'skin_name': 'AK-47 | Le...ice_last_365_day': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
skin_price_info.price_at_30_day
  Field required [type=missing, input_value={'skin_name': 'AK-47 | Le...ice_last_365_day': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
skin_price_info.price_at_365_day
  Field required [type=missing, input_value={'skin_name': 'AK-47 | Le...ice_last_365_day': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
INFO 2025-09-07 12:08:06,302 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-07 12:09:51,853 [main.py (startup)] BOT STARTED
INFO 2025-09-07 12:10:11,444 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK search
INFO 2025-09-07 12:10:15,983 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER state_user_router CALLBACK skins_search
ERROR 2025-09-07 12:10:17,040 [log.py (__call__)] 4 validation errors for SkinsOnPageSchema
skin_price_info.price
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.11/v/float_type
skin_price_info.price_at_1_day
  Field required [type=missing, input_value={'skin_name': 'AK-47 | Le...ice_last_365_day': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
skin_price_info.price_at_30_day
  Field required [type=missing, input_value={'skin_name': 'AK-47 | Le...ice_last_365_day': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
skin_price_info.price_at_365_day
  Field required [type=missing, input_value={'skin_name': 'AK-47 | Le...ice_last_365_day': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
Traceback (most recent call last):
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\log.py", line 29, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\user.py", line 64, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram_tool\depend\components\inner_middleware.py", line 42, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\handlers\states\user\router.py", line 62, in skins_search
    response = await client.skin.search_skins(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\infrastracture\http\fastfy\clients\skin.py", line 56, in search_skins
    return SkinsOnPageSchema(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\pydantic\main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 4 validation errors for SkinsOnPageSchema
skin_price_info.price
  Input should be a valid number [type=float_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.11/v/float_type
skin_price_info.price_at_1_day
  Field required [type=missing, input_value={'skin_name': 'AK-47 | Le...ice_last_365_day': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
skin_price_info.price_at_30_day
  Field required [type=missing, input_value={'skin_name': 'AK-47 | Le...ice_last_365_day': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
skin_price_info.price_at_365_day
  Field required [type=missing, input_value={'skin_name': 'AK-47 | Le...ice_last_365_day': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
INFO 2025-09-07 12:11:06,265 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-07 12:11:11,669 [main.py (startup)] BOT STARTED
INFO 2025-09-07 12:11:17,998 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK search
INFO 2025-09-07 12:11:21,750 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER state_user_router CALLBACK skins_search
ERROR 2025-09-07 12:11:22,763 [log.py (__call__)] 3 validation errors for SkinsOnPageSchema
skin_price_info.price_at_1_day
  Field required [type=missing, input_value={'skin_name': 'AK-47 | Le...ice_last_365_day': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
skin_price_info.price_at_30_day
  Field required [type=missing, input_value={'skin_name': 'AK-47 | Le...ice_last_365_day': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
skin_price_info.price_at_365_day
  Field required [type=missing, input_value={'skin_name': 'AK-47 | Le...ice_last_365_day': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
Traceback (most recent call last):
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\log.py", line 29, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\user.py", line 64, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram_tool\depend\components\inner_middleware.py", line 42, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\handlers\states\user\router.py", line 62, in skins_search
    response = await client.skin.search_skins(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\infrastracture\http\fastfy\clients\skin.py", line 56, in search_skins
    return SkinsOnPageSchema(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\pydantic\main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 3 validation errors for SkinsOnPageSchema
skin_price_info.price_at_1_day
  Field required [type=missing, input_value={'skin_name': 'AK-47 | Le...ice_last_365_day': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
skin_price_info.price_at_30_day
  Field required [type=missing, input_value={'skin_name': 'AK-47 | Le...ice_last_365_day': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
skin_price_info.price_at_365_day
  Field required [type=missing, input_value={'skin_name': 'AK-47 | Le...ice_last_365_day': None}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
INFO 2025-09-07 12:11:52,044 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-07 12:13:38,626 [main.py (startup)] BOT STARTED
INFO 2025-09-07 12:13:42,395 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK search
INFO 2025-09-07 12:13:46,296 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER state_user_router CALLBACK skins_search
INFO 2025-09-07 12:13:49,881 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-07 12:13:53,045 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-07 12:14:00,012 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK search
INFO 2025-09-07 12:14:03,187 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER state_user_router CALLBACK skins_search
INFO 2025-09-07 12:14:12,402 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER state_user_router CALLBACK skins_search
INFO 2025-09-07 12:14:16,393 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-07 12:14:19,671 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_skin_search
INFO 2025-09-07 12:14:25,099 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_skin_search
INFO 2025-09-07 12:14:28,550 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_skin_search
INFO 2025-09-07 12:14:42,636 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-07 12:39:00,766 [main.py (startup)] BOT STARTED
INFO 2025-09-07 12:39:28,721 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
ERROR 2025-09-07 12:39:29,876 [log.py (__call__)] 'UserPortfolioSkinSchema' object has no attribute 'name'
Traceback (most recent call last):
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\log.py", line 29, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\user.py", line 64, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram_tool\depend\components\inner_middleware.py", line 42, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\handlers\slash_commands\user\router.py", line 78, in portfolio
    reply_markup=paginate_buttons(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\utils\buttons\inline\user\buttons.py", line 41, in paginate_buttons
    compress_name = CompressName.compress(skin.name, "to")
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\pydantic\main.py", line 991, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'UserPortfolioSkinSchema' object has no attribute 'name'
INFO 2025-09-07 12:40:22,805 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-07 12:46:29,295 [main.py (startup)] BOT STARTED
INFO 2025-09-07 12:46:53,913 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
ERROR 2025-09-07 12:46:55,020 [log.py (__call__)] 'UserPortfolioSkinSchema' object has no attribute 'replace'
Traceback (most recent call last):
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\log.py", line 29, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\user.py", line 64, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram_tool\depend\components\inner_middleware.py", line 42, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\handlers\slash_commands\user\router.py", line 78, in portfolio
    reply_markup=paginate_buttons(
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\utils\buttons\inline\user\buttons.py", line 42, in paginate_buttons
    compress_name = CompressName.compress(skin, "to")
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\utils\compress.py", line 33, in compress
    skin_name = skin_name.replace(ptr, prt_value)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\pydantic\main.py", line 991, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'UserPortfolioSkinSchema' object has no attribute 'replace'
INFO 2025-09-07 12:47:06,068 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-07 12:47:25,331 [main.py (startup)] BOT STARTED
INFO 2025-09-07 12:47:34,360 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-07 12:47:43,663 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-07 12:55:15,815 [main.py (startup)] BOT STARTED
INFO 2025-09-07 12:55:22,325 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-07 12:55:35,381 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK click_portfolio_skin
INFO 2025-09-07 12:55:40,049 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_portfolio_skin
INFO 2025-09-07 12:55:47,021 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER user_callback_router CALLBACK paginate_portfolio_skin
INFO 2025-09-07 22:55:28,294 [main.py (startup)] BOT STARTED
INFO 2025-09-07 22:55:46,985 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK start
ERROR 2025-09-07 22:55:48,078 [user.py (__call__)] Middleware get user error 500 Произошла ошибка. Повторите попытку позже.
INFO 2025-09-07 22:55:56,391 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-07 22:56:48,296 [main.py (startup)] BOT STARTED
INFO 2025-09-07 22:56:59,325 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK start
INFO 2025-09-07 22:57:03,455 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK start
INFO 2025-09-07 22:57:07,907 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK start
INFO 2025-09-07 22:57:24,886 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-07 22:58:15,378 [main.py (startup)] BOT STARTED
INFO 2025-09-07 22:58:25,370 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK start
INFO 2025-09-07 22:58:25,776 [user.py (__call__)] New user in bot 2054556183 shayZi12345
INFO 2025-09-07 22:59:41,232 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER state_user_router CALLBACK login_state_code
ERROR 2025-09-07 22:59:41,794 [log.py (__call__)] 'login_users'
Traceback (most recent call last):
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\log.py", line 29, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\user.py", line 35, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram_tool\depend\components\inner_middleware.py", line 42, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\handlers\states\user\router.py", line 34, in login_state_code
    dispatcher["login_users"][message.from_user.id] = True
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 101, in __getitem__
    return self.workflow_data[item]
KeyError: 'login_users'
INFO 2025-09-07 23:00:28,260 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-07 23:01:23,790 [main.py (startup)] BOT STARTED
INFO 2025-09-07 23:01:32,523 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK start
INFO 2025-09-07 23:01:33,067 [user.py (__call__)] New user in bot 2054556183 shayZi12345
INFO 2025-09-07 23:01:56,822 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER state_user_router CALLBACK login_state_code
INFO 2025-09-07 23:02:01,024 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK start
INFO 2025-09-07 23:02:03,764 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK start
INFO 2025-09-07 23:02:05,061 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK start
INFO 2025-09-07 23:02:10,535 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
ERROR 2025-09-07 23:02:11,051 [log.py (__call__)] 'bool' object has no attribute 'steam_name'
Traceback (most recent call last):
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\log.py", line 29, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\user.py", line 72, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram_tool\depend\components\inner_middleware.py", line 42, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\handlers\slash_commands\user\router.py", line 77, in portfolio
    text=f"Портфолио для аккаунта: {user.steam_name}",
AttributeError: 'bool' object has no attribute 'steam_name'
INFO 2025-09-07 23:02:35,393 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-07 23:03:09,068 [main.py (startup)] BOT STARTED
INFO 2025-09-07 23:03:21,052 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-07 23:07:37,792 [main.py (startup)] BOT STARTED
INFO 2025-09-07 23:08:10,599 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK start
INFO 2025-09-07 23:08:15,166 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK start
INFO 2025-09-07 23:08:16,550 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK start
INFO 2025-09-07 23:08:17,610 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK start
INFO 2025-09-07 23:08:19,243 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK start
INFO 2025-09-07 23:08:28,061 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK start
INFO 2025-09-07 23:08:30,546 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK start
INFO 2025-09-07 23:08:33,688 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-07 23:08:47,185 [main.py (startup)] BOT STARTED
INFO 2025-09-07 23:08:52,148 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK start
INFO 2025-09-07 23:08:52,530 [user.py (__call__)] New user in bot 2054556183 shayZi12345
INFO 2025-09-07 23:09:07,899 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER state_user_router CALLBACK login_state_code
INFO 2025-09-07 23:09:14,288 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK start
INFO 2025-09-07 23:09:16,335 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK start
INFO 2025-09-07 23:09:17,537 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK start
INFO 2025-09-07 23:09:18,959 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK start
INFO 2025-09-07 23:09:24,945 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
ERROR 2025-09-07 23:09:24,946 [log.py (__call__)] portfolio() missing 1 required positional argument: 'user'
Traceback (most recent call last):
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\log.py", line 29, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\bot\bot\middleware\user.py", line 73, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram_tool\depend\components\inner_middleware.py", line 42, in __call__
    return await handler(event, data)
  File "C:\Users\dyadh\OneDrive\Рабочий стол\FastFy\venv\lib\site-packages\aiogram\dispatcher\event\handler.py", line 43, in call
    return await wrapped()
TypeError: portfolio() missing 1 required positional argument: 'user'
INFO 2025-09-07 23:09:37,123 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-07 23:09:51,910 [main.py (startup)] BOT STARTED
INFO 2025-09-07 23:10:06,641 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-07 23:10:19,928 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-07 23:10:43,214 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK account
INFO 2025-09-07 23:15:21,669 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-07 23:19:31,293 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-07 23:20:55,170 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-07 23:22:03,952 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-07 23:22:07,066 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-07 23:24:48,418 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-07 23:24:53,209 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-07 23:26:31,670 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-07 23:27:17,054 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-07 23:27:29,906 [main.py (shutdown)] BOT SHUTDOWN
INFO 2025-09-07 23:32:15,890 [main.py (startup)] BOT STARTED
INFO 2025-09-07 23:32:28,659 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-07 23:33:20,722 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-07 23:34:40,993 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-07 23:41:34,954 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-07 23:43:45,655 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-07 23:44:26,208 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-07 23:46:18,703 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-07 23:46:21,929 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-07 23:46:59,896 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-07 23:49:39,020 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-07 23:49:54,493 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-07 23:52:20,733 [log.py (__call__)] USER 2054556183~shayZi12345 ROUTER slash_commands_user_router CALLBACK portfolio
INFO 2025-09-07 23:53:21,514 [main.py (shutdown)] BOT SHUTDOWN
